# Generated by Django 3.2.7 on 2021-09-20 13:51

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(default='empty.png', upload_to=shop.models.get_path_upload_to),
        ),
    ]
