# Generated by Django 3.2.7 on 2021-09-22 11:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='number',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(9), django.core.validators.MinLengthValidator(9)]),
        ),
    ]
