# Generated by Django 3.2.7 on 2021-09-23 11:52

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210923_1120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'managed': True, 'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='usermodel',
            options={'ordering': ('-last_name', '-first_name'), 'verbose_name': 'UserModel', 'verbose_name_plural': 'UserModels'},
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AlterModelTable(
            name='address',
            table='',
        ),
    ]
